name: trustfall
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  outline_material_icons: ^0.1.1
  cupertino_icons: ^0.1.3
  snack: ^1.0.4
  shared_preferences: ^0.5.8
  shimmer: ^1.1.1
  pull_to_refresh: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway/Raleway-Bold.ttf
          weight: 700